apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service-deployment
  labels:
    app: appointment-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
        - name: appointment-service-server
          image: iit14.azurecr.io/appointment-api:latest
          ports:
            - containerPort: 4500
---
apiVersion: v1
kind: Service
metadata:
  name: appointment-service
  labels:
    app: appointment-service
spec:
  type: LoadBalancer
  selector:
    app: appointment-service
  ports:
    - port: 5500
      targetPort: 4500
