apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service-deployment
  labels:
    app: profile-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: profile-service
  template:
    metadata:
      labels:
        app: profile-service
    spec:
      containers:
        - name: profile-service-server
          image: iit14.azurecr.io/patient-api:latest
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: profile-service
  labels:
    app: profile-service
spec:
  type: LoadBalancer
  selector:
    app: profile-service
  ports:
    - port: 5000
      targetPort: 4000
